import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.58.0";
import { generateTextWithFallback } from "../_shared/unifiedAIFallback.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const AUDIENCE_PERSONAS = {
  technical: {
    complexity: 'high',
    jargon: 'allowed',
    detail_level: 'comprehensive',
    include_code: true,
    tone: 'professional'
  },
  community: {
    complexity: 'medium',
    jargon: 'minimal',
    detail_level: 'engaging',
    include_code: false,
    tone: 'friendly'
  },
  executive: {
    complexity: 'low',
    jargon: 'business_terms',
    detail_level: 'summary',
    include_code: false,
    tone: 'professional'
  },
  general: {
    complexity: 'low',
    jargon: 'none',
    detail_level: 'accessible',
    include_code: false,
    tone: 'welcoming'
  }
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    const { 
      content_type, 
      audience_type = 'community', 
      source_data, 
      format = 'markdown',
      title,
      additional_context 
    } = await req.json();

    console.log(`Generating ${content_type} for ${audience_type} audience`);

    const persona = AUDIENCE_PERSONAS[audience_type as keyof typeof AUDIENCE_PERSONAS] || AUDIENCE_PERSONAS.general;

    // Build NLG prompt
    const systemPrompt = `You are Eliza, the autonomous AI operator of the XMRT-DAO Ecosystem, a decentralized community focused on privacy, education, and Monero mining.

AUDIENCE: ${audience_type}
COMPLEXITY LEVEL: ${persona.complexity}
TONE: ${persona.tone}
TECHNICAL JARGON: ${persona.jargon}
DETAIL LEVEL: ${persona.detail_level}

CONTENT TYPE: ${content_type}
OUTPUT FORMAT: ${format}

Transform the provided data into ${content_type} that:
1. Matches the audience's technical level (${persona.complexity} complexity)
2. Uses a ${persona.tone} tone
3. Provides ${persona.detail_level} detail
4. ${persona.include_code ? 'Includes code examples where relevant' : 'Avoids technical code'}
5. Highlights key insights and actionable information
6. Maintains XMRT-DAO's values of transparency, education, and community empowerment

${additional_context ? `Additional Context: ${additional_context}` : ''}`;

    const userPrompt = `Generate a ${content_type} based on this data:

${JSON.stringify(source_data, null, 2)}

${title ? `Title: ${title}` : ''}

Create engaging, informative content that this audience will find valuable and easy to understand.`;

    const staticFallback = `## ${title || `Generated ${content_type}`}

${content_type} generated for ${audience_type} audience.

### Data Summary
${JSON.stringify(source_data, null, 2).substring(0, 500)}

---
*Generated by Eliza - XMRT-DAO Ecosystem*`;

    let generatedContent: string;
    let aiProvider = 'static_fallback';

    try {
      console.log('🔄 Generating content with AI fallback cascade...');
      generatedContent = await generateTextWithFallback(
        userPrompt, 
        systemPrompt, 
        {
          temperature: 0.7,
          maxTokens: 2000,
          useFullElizaContext: false
        }
      );
      aiProvider = 'ai_cascade';
      console.log('✅ Content generated via AI cascade');
    } catch (aiError) {
      console.warn('⚠️ All AI providers failed, using static fallback:', aiError);
      generatedContent = staticFallback;
    }

    // Store generated content
    const { data: contentRecord, error: insertError } = await supabase
      .from('nlg_generated_content')
      .insert({
        content_type,
        audience_type,
        title: title || `Generated ${content_type}`,
        content: generatedContent,
        format,
        source_data,
        metadata: {
          persona_used: persona,
          additional_context,
          ai_provider: aiProvider
        }
      })
      .select()
      .single();

    if (insertError) {
      console.error('Error storing content:', insertError);
    }

    // Log activity
    await supabase.from('eliza_activity_log').insert({
      activity_type: 'nlg_generation',
      title: `Generated ${content_type}`,
      description: `Created ${content_type} for ${audience_type} audience`,
      status: 'completed',
      metadata: {
        content_type,
        audience_type,
        format,
        content_length: generatedContent.length,
        content_id: contentRecord?.id,
        ai_provider: aiProvider
      }
    });

    return new Response(
      JSON.stringify({
        success: true,
        content: generatedContent,
        content_id: contentRecord?.id,
        metadata: {
          content_type,
          audience_type,
          format,
          persona_used: persona,
          ai_provider: aiProvider
        }
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      }
    );

  } catch (error) {
    console.error('NLG generation error:', error);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      }
    );
  }
});
