project_id = "vawouugtzwmejxqkeqqj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[edge_runtime]
enabled = true
policy = ["permissive"]
inspector_port = 8083

[analytics]
enabled = false
port = 54327
vector_port = 54328
gcp_jwt_path = ""

[experimental]
oriole_mode = false
