-- Migration: Add deliverable tracking & notification fields to tasks table
-- Issue: #2279 - Enhance Task Completion Workflow
-- Generated by Antigravity on 2026-03-03
-- 1. Add new columns to tasks table
ALTER TABLE public.tasks
ADD COLUMN IF NOT EXISTS expected_deliverables TEXT,
    ADD COLUMN IF NOT EXISTS deliverable_storage_path TEXT,
    ADD COLUMN IF NOT EXISTS notification_recipients TEXT [] DEFAULT ARRAY []::TEXT [];
COMMENT ON COLUMN public.tasks.expected_deliverables IS 'Human-readable description of what deliverables the agent should produce (e.g. "Market Research Report in PDF")';
COMMENT ON COLUMN public.tasks.deliverable_storage_path IS 'Intended storage location for deliverables (e.g. "Google Drive/XMRT-DAO/Awapuhi Project/Reports")';
COMMENT ON COLUMN public.tasks.notification_recipients IS 'Array of email addresses to notify upon task completion. Falls back to EXECUTIVE_EMAIL env var if empty.';
-- 2. Update the existing notify_task_completion trigger function to include new fields
CREATE OR REPLACE FUNCTION notify_task_completion() RETURNS TRIGGER AS $$
DECLARE project_url TEXT;
service_key TEXT;
BEGIN -- Get settings (graceful fallback if not set)
project_url := current_setting('app.settings.supabase_url', true);
service_key := current_setting('app.settings.service_role_key', true);
-- Only proceed if status changed to COMPLETED
IF (
    OLD.status IS DISTINCT
    FROM NEW.status
)
AND (NEW.status = 'COMPLETED') THEN -- Log to webhook_logs for debugging
INSERT INTO webhook_logs (
        webhook_name,
        trigger_table,
        trigger_operation,
        payload,
        status,
        event_source,
        event_type
    )
VALUES (
        'task_completed',
        'tasks',
        'UPDATE',
        jsonb_build_object(
            'id',
            NEW.id,
            'title',
            NEW.title,
            'status',
            NEW.status,
            'proof_of_work_link',
            NEW.proof_of_work_link,
            'expected_deliverables',
            NEW.expected_deliverables,
            'deliverable_storage_path',
            NEW.deliverable_storage_path,
            'notification_recipients',
            NEW.notification_recipients,
            'assignee_agent_id',
            NEW.assignee_agent_id,
            'completed_at',
            NEW.completed_at,
            'resolution_notes',
            NEW.resolution_notes
        ),
        'pending',
        'supabase',
        'task:completed'
    );
-- Invoke the task-completion-notifier edge function via pg_net
IF project_url IS NOT NULL
AND service_key IS NOT NULL THEN PERFORM net.http_post(
    url := project_url || '/functions/v1/task-completion-notifier',
    headers := jsonb_build_object(
        'Authorization',
        'Bearer ' || service_key,
        'Content-Type',
        'application/json'
    ),
    body := jsonb_build_object(
        'type',
        'UPDATE',
        'table',
        'tasks',
        'schema',
        'public',
        'record',
        row_to_json(NEW),
        'old_record',
        row_to_json(OLD)
    )
);
ELSE RAISE WARNING 'Task completed but app.settings.supabase_url or service_role_key not set. Webhook not sent.';
END IF;
END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- 3. Re-create the trigger (replacing the old one)
DROP TRIGGER IF EXISTS trigger_notify_task_completion ON public.tasks;
CREATE TRIGGER trigger_notify_task_completion
AFTER
UPDATE ON public.tasks FOR EACH ROW EXECUTE FUNCTION notify_task_completion();