-- Migration to add proof_of_work_link and task completion webhook
-- Generated by Antigravity on 2026-02-12
-- 1. Add proof_of_work_link column to tasks table (if not exists)
ALTER TABLE public.tasks
ADD COLUMN IF NOT EXISTS proof_of_work_link TEXT;
-- 2. Create function to notify task completion
CREATE OR REPLACE FUNCTION notify_task_completion() RETURNS TRIGGER AS $$
DECLARE project_url TEXT;
service_key TEXT;
BEGIN -- Get settings (graceful fallback if not set, though they should be)
project_url := current_setting('app.settings.supabase_url', true);
service_key := current_setting('app.settings.service_role_key', true);
-- Only proceed if status changed to COMPLETED
IF (
    OLD.status IS DISTINCT
    FROM NEW.status
)
AND (NEW.status = 'COMPLETED') THEN -- Log to webhook_logs for debugging (optional but good practice based on existing patterns)
INSERT INTO webhook_logs (
        webhook_name,
        trigger_table,
        trigger_operation,
        payload,
        status,
        event_source,
        event_type
    )
VALUES (
        'task_completed',
        'tasks',
        'UPDATE',
        jsonb_build_object(
            'id',
            NEW.id,
            'title',
            NEW.title,
            'proof_of_work_link',
            NEW.proof_of_work_link
        ),
        'pending',
        'supabase',
        'task:completed'
    );
-- If pg_net extension is available and settings are present, invoke the function
IF project_url IS NOT NULL
AND service_key IS NOT NULL THEN PERFORM net.http_post(
    url := project_url || '/functions/v1/task-completion-notifier',
    headers := jsonb_build_object(
        'Authorization',
        'Bearer ' || service_key,
        'Content-Type',
        'application/json'
    ),
    body := jsonb_build_object(
        'type',
        'UPDATE',
        'table',
        'tasks',
        'schema',
        'public',
        'record',
        row_to_json(NEW),
        'old_record',
        row_to_json(OLD)
    )
);
ELSE -- Fallback logging if settings are missing
RAISE WARNING 'Task completed but app.settings.supabase_url or service_role_key not set. Webhook not sent.';
END IF;
END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- 3. Create Trigger
DROP TRIGGER IF EXISTS trigger_notify_task_completion on public.tasks;
CREATE TRIGGER trigger_notify_task_completion
AFTER
UPDATE ON public.tasks FOR EACH ROW EXECUTE FUNCTION notify_task_completion();