-- Migration to add missing columns for task completion logic
-- Generated by Antigravity on 2026-02-07

ALTER TABLE public.tasks 
ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS completed_checklist_items TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS resolution_notes TEXT;

-- Verify columns (optional, for manual check)
-- SELECT column_name FROM information_schema.columns WHERE table_name = 'tasks';
